allowBuilds:
  esbuild: true
  vitepress-versioning-plugin@https://codeload.github.com/FabricMC/vitepress-versioning-plugin/tar.gz/65bae2d4dfee47d0d233f688844cbb572c534ef5: true

minimumReleaseAge: 4320 # three days

patchedDependencies:
  vitepress@2.0.0-alpha.20: patches/vitepress@2.0.0-alpha.20.patch

savePrefix: ""

update:
  ignoreDeps:
    - typescript
